---
- hosts: windows
  gather_facts: false
  vars_prompt:
    - name: ansible_ssh_pass
      prompt: Windows password
      private: yes
      confirm: no
  tasks:
  - name: Install langpack
    script: ps-files/install-langpack.ps1
  - name: Restart computer
    win_reboot:
  - name: Setup language
    script: ps-files/setup-language.ps1
  - name: Restart computer
    win_reboot:
