---
- hosts: windows
  gather_facts: false
  vars_prompt:
    - name: ansible_ssh_pass
      prompt: Windows password
      private: yes
      confirm: no
  tasks:
  - name: Install dotnet framework sdk.
    script: ps-files/install-netframework-sdk.ps1
