---
- hosts: windows
  gather_facts: false
  vars_prompt:
    - name: ansible_ssh_pass
      prompt: Enter password for windows server.
      private: yes
      confirm: no
  tasks:
  - name: Install .NET 5 Runtime
    script: ps-files/install-dotnet5-runtime.ps1
  tasks:
  - name: Install node.js
    script: ps-files/install-nodejs.ps1
