---
- hosts: windows
  gather_facts: false
  vars_prompt:
    - name: ansible_ssh_pass
      prompt: Enter password
      private: yes
      confirm: no
  roles:
    - OdpNet
    - aspnet5
  tasks:
    # Need iis setup
    # - name: Install .NET 5 Runtime via chololatey
    #   win_chocolatey:
    #     name: dotnet-5.0-windowshosting
    #     state: present
    - name: Install node.js via chololatey
      win_chocolatey:
        name: nodejs
        state: present
    - name: Install python via chololatey
      win_chocolatey:
        name: python
        state: present
    - name: Install Ruby on Rails via chololatey
      win_chocolatey:
        name: railsinstaller
        state: present
    - name: Install go via chololatey
      win_chocolatey:
        name: golang
        version: 1.15.5
        state: present
