---
- name: Download
  win_get_url:
    url: https://download.visualstudio.microsoft.com/download/pr/b6271a4b-db02-4245-bf99-974ea96b7ca3/29389344a55c6792bd4e717a254168a2/dotnet-hosting-5.0.1-win.exe
    dest: C:\Users\azureuser\dotnet-hosting-5.0.1-win.exe
- name: Install
  win_command: C:\Users\azureuser\dotnet-hosting-5.0.1-win.exe /install /quiet

# Needs IIS setup...
# - name: Install ASP.NET 5 hosting
#   win_package:
#     path: https://download.visualstudio.microsoft.com/download/pr/b6271a4b-db02-4245-bf99-974ea96b7ca3/29389344a55c6792bd4e717a254168a2/dotnet-hosting-5.0.1-win.exe
#     product_id: dotnet5
#     state: present
